/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.deepinid.xml -p deepinid_interface -c DeepinIDInterface -l DbusExtendedAbstractInterface -N
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "deepinid_interface.h"

/*
 * Implementation of interface class DeepinIDInterface
 */

DeepinIDInterface::DeepinIDInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qDBusRegisterMetaType<UserInfo>();
//    qDBusRegisterMetaType<Hardware>();
}

DeepinIDInterface::~DeepinIDInterface()
{
}

